project:
  type: book

execute:
  freeze: auto

book:
  title: "Economic Columns Analysis"
  author: "Jaeseong Choe"
  date: 2023/03/07
  downloads: [pdf]
  repo-url: https://github.com/sorrychoe/economic_analysis
  repo-actions: edit
  search: true
  reader-mode: true
  sidebar:
    style: "docked"
  chapters:
    - index.qmd
    - part: "Reports"
      chapters:
        - economic_columns_clustering.qmd
        - economic_topic_modeling.qmd

format:
  bookup-html